name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/adoptopenjdk-17-hotspot
      ANDROID_SDK_ROOT: ${{ runner.home }}/Android/Sdk

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Download Android SDK command line tools
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        cd $ANDROID_SDK_ROOT/cmdline-tools/latest
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -o commandlinetools.zip
        rm commandlinetools.zip

    - name: Setup Android SDK
      run: |
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build APK Release
      run: ./gradlew assembleRelease --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk
